- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    name_prefix: "demo2"
    aws_ssh_key_path: "{{ playbook_dir }}/../.ssh/"
    aws_ssh_key_private: "id_rsa"
    vpc_network: "10.250.252.0/24"
    vpc_subnet:  "10.250.252.0/28"

  tasks:
  - include_vars:
      file: "{{ aws_ssh_key_path }}/aws_console_edwardperry1_root_account.yml"

  - name: Getting Centos AMI ID
    ec2_ami_facts:
      owners: "679593333241"
      filters:
        product-code: aw0evgkw8e5c1q413zgy5pjce
        architecture: "x86_64"
        name: "CentOS Linux 7 x86_64 HVM EBS ENA*"
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"
    register: ami_id

  - debug: 
      var: ami_id

  - name: Make Sure Keypair exists
    ec2_key:
      name: "{{ name_prefix }}_ssh_key"
      key_material: "{{ lookup('file', '{{ aws_ssh_key_path }}/{{ aws_ssh_key_private }}.pub') }}"
      force: false
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"
    register: key_pair

  - debug:
      var: key_pair

  - name: create VPC
    ec2_vpc_net:
      name: "{{ name_prefix }}_{{ vpc_network }}"
      cidr_block: "{{ vpc_network }}"
      state: present
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"
    register: vpc
  
  - debug:
      var: vpc

  - name: associate subnet to the VPC
    ec2_vpc_subnet:
     state: present
     vpc_id: "{{ vpc.vpc.id }}"
     cidr: "{{ vpc_subnet }}"
     map_public: true
     aws_access_key: "{{ AWSAccessKeyId }}"
     aws_secret_key: "{{ AWSSecretKey }}"
    register: subnet

  - debug:
      var: subnet 

  - name: create IGW
    ec2_vpc_igw:
     vpc_id: "{{ vpc.vpc.id }}"
     state: "present"
     aws_access_key: "{{ AWSAccessKeyId }}"
     aws_secret_key: "{{ AWSSecretKey }}"
    register: igw

  - debug:
      var: igw

  - name: Route IGW
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      subnets:
        - "{{ subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id  }}"
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"

  - name: "Create VPC Security Group"
    ec2_group:
      name: "{{ name_prefix }}_all"
      vpc_id: "{{ vpc.vpc.id }}"
      description: "Default access"
      rules:
      - proto: tcp
        ports:
        - 22
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22,80
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"
    register: security_group

  - debug:
      var: security_group

  - name: "Provision an instances"
    ec2:
      id: "{{ name_prefix }}_server"
      instance_type: t2.micro
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      image: "{{ ami_id.images[0].image_id }}"
      volumes:
              #- device_name: /dev/xvda
      - device_name: /dev/sda1
        volume_size: 120
        delete_on_termination: true
      key_name: "{{ key_pair.key.name }}"
      group:
      - "{{ security_group.group_name }}"
      instance_tags:
        Name: "{{ name_prefix }}_server"
      wait: yes
      count: 1
      state: present
      aws_access_key: "{{ AWSAccessKeyId }}"
      aws_secret_key: "{{ AWSSecretKey }}"
    register: ec2

  - debug:
      var: ec2


